<a href="https://colab.research.google.com/github/Optimus2007/Student_Performance_Prediction/blob/main/Student_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

Importing the libraries

In [23]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [24]:
dataset = pd.read_csv('Student_performance2.csv')

Encoding the categorical data

In [30]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()#i am using label encoder because yes no is a order and has a priorities
dataset['Extracurricular Activities'] = le.fit_transform(dataset['Extracurricular Activities'])
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)

[[ 7 99  1  9  1]
 [ 4 82  0  4  2]
 [ 8 51  1  7  2]
 [ 5 52  1  5  2]
 [ 7 75  0  8  5]
 [ 3 78  0  9  6]
 [ 7 73  1  5  6]
 [ 8 45  1  4  6]
 [ 5 77  0  8  2]
 [ 4 89  0  4  0]
 [ 8 91  0  4  5]
 [ 8 79  0  6  2]
 [ 3 47  0  9  2]
 [ 6 47  0  4  2]
 [ 5 79  0  7  8]
 [ 2 72  0  4  3]
 [ 8 73  1  8  4]
 [ 6 83  1  7  2]
 [ 2 54  1  4  9]
 [ 5 75  0  7  0]
 [ 1 99  1  4  3]
 [ 6 96  0  9  0]
 [ 9 74  1  7  6]
 [ 1 85  0  5  6]
 [ 3 61  0  6  3]
 [ 7 62  1  7  4]
 [ 4 79  0  8  9]
 [ 9 84  1  6  6]
 [ 3 94  1  6  5]
 [ 5 90  1  4  3]
 [ 3 61  1  7  3]
 [ 7 44  1  9  1]
 [ 5 70  1  6  9]
 [ 9 52  1  8  1]
 [ 7 67  1  9  3]
 [ 2 97  1  9  4]
 [ 4 59  0  8  3]
 [ 9 72  0  8  2]
 [ 2 55  1  4  1]
 [ 9 68  0  5  3]
 [ 5 62  0  7  4]
 [ 2 63  1  6  0]
 [ 4 73  1  7  0]
 [ 7 46  0  9  5]
 [ 8 77  1  6  4]
 [ 3 76  1  4  3]
 [ 1 43  1  7  0]
 [ 4 73  0  4  6]
 [ 2 81  1  4  3]
 [ 8 61  0  7  2]]


Spliting the dataset into Training set and Test set

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Training the Multiple Linear Regression model on the Training set

In [32]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

Predicting the Test set results

In [33]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[74.17 74.  ]
 [71.97 73.  ]
 [84.2  84.  ]
 [38.01 39.  ]
 [44.28 45.  ]
 [81.69 83.  ]
 [29.17 32.  ]
 [34.87 36.  ]
 [71.95 73.  ]
 [66.88 66.  ]]


In [34]:
regressor.predict([[6,40,1,5,2]])#to predict some unique data

array([26.25])